### PR TITLE
Change the internals of OrtString for cheap &str and &Cstr conversions

### PR DESCRIPTION
**Pull request by cchalmers**
I'm still not happy with how `run` is. My first attempt at rewriting it failed but this came out of it.

### CODE REVIEW

**Review by basile-henry — APPROVED** [review]
Looks great!

But doesn't this need a custom `Drop` instance?

In the future we can parameterize it with an Allocator if we end up doing that

**Comment by cchalmers** [comment]
The drop instance hasn't changed, it's just below the visible diff. I'm not actually sure why they even have a custom allocator for these kinds of strings since they're very small and you don't need to get them very often (normally just the once). Maybe there's some other part of the API where it's useful to have a custom allocator.

Also, annoyingly you can't really use the rust allocator here before because their free doesn't provide enough infomation (the rust allocator likes to know the size of what you're freeing).

**Comment by basile-henry** [comment]
@cchalmers I think they have a custom allocator for the output tensors. I guess that can be useful when allocating for the GPU? And for some reason they also use it for all the strings :man_shrugging:

**Comment by cchalmers** [comment]
For output tensors you can just give it your own pointer (this is how I can make a `Vec` a tensor).

**Comment by basile-henry** [comment]
Yes I know, but they also have the option to have ORT allocate it for you, which might explain the whole allocator API they have going on

**Comment by cchalmers** [comment]
Right, I guess if you don't know the size of the output before hand it could be useful.

**Pull request merged**
