### PR TITLE
Chris

### PR DESCRIPTION
**Pull request by cchalmers**
Lots of macro stuff, still a WIP but should be ready by Tuesday.

### CODE REVIEW

**Review by basile-henry — APPROVED** [review]
Looks great! :)

How do you currently build and test the project?
I have been working on a nix build but it's going pretty slowly. Ideally I would want to be able to build it without nix so it's easier to setup things like Github Actions for CI, so I'm interested to know what your workflow is like. :smile:

**Comment by basile-henry** [comment]
Would you mind if I merge this to `master`? :)

**Comment by cchalmers** [comment]
Sure, you can merge it when you like if it helps you (I can always just make a another PR). There's still a few things I want to work on but I think it's getting close.

**Comment by basile-henry** [comment]
Ok, it can wait if it's easier for you. You might have to rebase then, it won't be much :sweat_smile:

**Pull request merged**
